version: "3.8"

networks:
  ft_trans:
    name: ft_transcendence
    driver: bridge

services:
  transDB:
    image: postgres:16
    ports:
      - 5434:5432
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - ft_trans
    restart: unless-stopped

  front:
    build: front
    container_name: front
    restart: always
    ports:
      - 3000:3000
    networks:
      - ft_trans
    depends_on:
      - back
    volumes:
      - ./front:/app
      - /app/node_modules
  
  back:
    build: back
    container_name: back
    restart: always
    ports:
      - 3333:3333
    networks:
      - ft_trans
    depends_on:
      - transDB
    links:
      - transDB
    volumes:
      - ./back:/app
      - /app/node_modules